# .ci.yaml
on:
  push:
  pull_request:

jobs:  
  run-tests: 
    concurrency:
        group: ${{ github.workflow }}-${{ matrix.os }}
    strategy: 
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Print Environment Variables
        run: |
            echo "DB_CONNECTION_STRING=$DB_CONNECTION_STRING"
            echo "DB_NAME=$DB_NAME"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: |
            go env
            cd backend-go
            go get github.com/stretchr/testify
            go install github.com/go-gremlins/gremlins/cmd/gremlins@v0.4.0
      - name: Build Backend
        run: |
            cd backend-go
            go build ./...
      - name: Test and Coverage
        run: |
            cd backend-go
            cd controllers
            go test
            gremlins unleash
